user                            root;
worker_processes                auto;

error_log                       /var/log/nginx/error.log warn;

events {
    worker_connections          1024;
}

http {
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    off;
    access_log                  off;
    keepalive_timeout           3000;
    server {
        listen 80 default_server;
        server_name localhost;
        absolute_redirect off;
        root /usr/share/nginx/html;

        error_page 404 /404.html;

        location = /supported-games/7d2d {
            return 301 /supported-games/official/7d2d/;
        }

        location = /supported-games/7d2d/ {
            return 301 /supported-games/official/7d2d/;
        }

        location / {
            try_files $uri $uri/ =404;
        }

        location = /404.html {
            internal;
        }
    }
}
